(in-package :lambda64.tests)

(defstruct runtime-sample
  name
  payload)

(defclass runtime-box ()
  ((value :initarg :value :accessor runtime-box-value)))

(defgeneric runtime-box-double (box))

(defmethod runtime-box-double ((box runtime-box))
  (* 2 (runtime-box-value box)))

(define-test "runtime.integer-arithmetic" ()
  (let* ((large (ash 1 100))
         (product (* large (+ large 17))))
    (is (= (+ 40 2) 42))
    (is (= (- 7 19) -12))
    (is (= (truncate product large) (+ large 17)))
    (is (= (mod (+ product 5) large) 5))
    (is (= (logxor #x55aa #x0ff0) #x5a5a))))

(define-test "runtime.arrays-and-strings" ()
  (let ((matrix (make-array '(8 16) :initial-element 0))
        (vector (make-array 128 :element-type '(unsigned-byte 8)))
        (bits (make-array 64 :element-type 'bit :initial-element 0))
        (text (copy-seq "Lambda64 runtime")))
    (dotimes (row 8)
      (dotimes (column 16)
        (setf (aref matrix row column) (+ (* row 16) column))))
    (dotimes (i (length vector))
      (setf (aref vector i) (mod (* i 17) 256)))
    (dotimes (i (length bits))
      (setf (aref bits i) (mod i 2)))
    (is (= (aref matrix 7 15) 127))
    (is (= (aref vector 127) (mod (* 127 17) 256)))
    (is (= (count 1 bits) 32))
    (is (string= (subseq text 0 8) "Lambda64"))))

(define-test "runtime.sequences" ()
  (let* ((source (loop for i below 100 collect i))
         (evens (remove-if #'oddp source))
         (squares (mapcar (lambda (value) (* value value)) evens)))
    (is (= (length evens) 50))
    (is (= (first squares) 0))
    (is (= (car (last squares)) (* 98 98)))
    (is (= (reduce #'+ source) 4950))))

(define-test "runtime.hash-tables" ()
  (let ((table (make-hash-table :test #'equal)))
    (dotimes (i 1024)
      (setf (gethash (format nil "key-~D" i) table) (* i i)))
    (is (= (hash-table-count table) 1024))
    (dotimes (i 1024)
      (multiple-value-bind (value presentp)
          (gethash (format nil "key-~D" i) table)
        (is presentp)
        (is (= value (* i i)))))
    (dotimes (i 512)
      (remhash (format nil "key-~D" i) table))
    (is (= (hash-table-count table) 512))))

(define-test "runtime.closures-and-values" ()
  (flet ((make-adder (base)
           (lambda (value) (+ base value)))
         (three-values ()
           (values :first 2 3)))
    (let ((add-37 (make-adder 37)))
      (is (= (funcall add-37 5) 42)))
    (multiple-value-bind (first second third)
        (three-values)
      (is (eq first :first))
      (is (= second 2))
      (is (= third 3)))))

(define-test "runtime.conditions-and-unwind" ()
  (let ((cleanup-ran nil)
        (caught nil))
    (handler-case
        (unwind-protect
             (error "intentional runtime condition")
          (setf cleanup-ran t))
      (error (condition)
        (declare (ignore condition))
        (setf caught t)))
    (is cleanup-ran)
    (is caught)))

(define-test "runtime.symbols-and-packages" ()
  (let ((name "LAMBDA64-RUNTIME-TEST-TEMPORARY-SYMBOL"))
    (multiple-value-bind (symbol status)
        (intern name :lambda64.tests)
      (declare (ignore status))
      (unwind-protect
           (multiple-value-bind (found found-status)
               (find-symbol name :lambda64.tests)
             (is (eq found symbol))
             (is found-status)
             (is (eq (symbol-package symbol) (find-package :lambda64.tests))))
        (unintern symbol :lambda64.tests)))))

(define-test "runtime.structures-and-clos" ()
  (let* ((structure (make-runtime-sample :name :sample
                                         :payload (vector 1 2 3 4)))
         (instance (make-instance 'runtime-box :value 21)))
    (mezzano.extensions:gc :full t)
    (is (eq (runtime-sample-name structure) :sample))
    (is (= (aref (runtime-sample-payload structure) 3) 4))
    (is (= (runtime-box-double instance) 42))))

(define-test "runtime.weak-pointer-live-value" ()
  (let* ((value (list :still :live))
         (pointer (mezzano.extensions:make-weak-pointer value)))
    (mezzano.extensions:gc :full t)
    (is (eq (mezzano.extensions:weak-pointer-value pointer) value))))
