(in-package :mezzano.internals)
(defparameter *file-server-host-ip* "10.0.2.2")
(defparameter *home-directory-path* "REMOTE:/Users/ivory/Project/LBuild/home/")
(defparameter *mezzano-source-path* "REMOTE:/Users/ivory/Project/LBuild/Lambda64/")
(setf *compile-parallel* t)
