#!/usr/bin/env bash
# Every DISPATCH-* operator called inside dispatch.lisp must actually be defined
# there.  DISPATCH-DELAYED called DISPATCH-AFTER's non-existent sibling
# DISPATCH-AT, so every delayed submission -- IP retransmit and outstanding-send
# expiry among them -- died with an undefined-function error at runtime.  The
# warm module's compile does not surface this as a build warning.
set -euo pipefail

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
repo_root=$(cd "$script_dir/../.." && pwd)
source_file=${DISPATCH_SOURCE:-"$repo_root/system/dispatch.lisp"}

python3 - "$source_file" "${DISPATCH_CALLS_MUTATION_RUN:-}" <<'PY'
from pathlib import Path
import re, sys

source = Path(sys.argv[1]).read_text(encoding="utf-8")
if sys.argv[2]:
    source = source.replace("(dispatch-after function (delay-to-run-time delay)",
                            "(dispatch-at function (delay-to-run-time delay)", 1)
    source = source.replace(":target queue\n", "", 1)

# Strip line comments and strings so neither contributes spurious calls.
stripped = re.sub(r'"(?:[^"\\]|\\.)*"', '""', source)
stripped = re.sub(r";[^\n]*", "", stripped)

defined = set(re.findall(r"\(defun\s+([a-z0-9%-]+)", stripped))
defined |= set(re.findall(r"\(defmacro\s+([a-z0-9%-]+)", stripped))
defined |= set(re.findall(r"\(defgeneric\s+([a-z0-9%-]+)", stripped))
# Slot readers/accessors generated by DEFCLASS.
defined |= set(re.findall(r":(?:reader|accessor|writer)\s+([a-z0-9%-]+)", stripped))
# Class names appear in operator position inside DEFCLASS supers and type
# specifiers; they are not calls.
defined |= set(re.findall(r"\(defclass\s+([a-z0-9%-]+)", stripped))
defined |= set(re.findall(r"\(defstruct\s+\(?([a-z0-9%-]+)", stripped))

called = set(re.findall(r"\((dispatch-[a-z0-9-]+)[\s)]", stripped))
called |= set(re.findall(r"#'(dispatch-[a-z0-9-]+)", stripped))

missing = sorted(c for c in called if c not in defined)
if missing:
    raise SystemExit("dispatch.lisp calls undefined operators: " + ", ".join(missing))

# DISPATCH-AFTER runs in the caller's thread, which need not have a dispatch
# context.  It must hand its QUEUE to MAKE-SOURCE; the default target reads
# *LOCAL-CONTEXT* and fails with no applicable method for CONTEXT-GLOBAL-QUEUE.
after = stripped[stripped.index("(defun dispatch-after"):]
after = after[:after.index("(defun ", 1)]
if ":target queue" not in after:
    raise SystemExit("DISPATCH-AFTER must pass :TARGET QUEUE to MAKE-SOURCE")
print(f"dispatch internal-call contract passed ({len(called)} dispatch operators)")
PY

if [[ -z "${DISPATCH_CALLS_MUTATION_RUN:-}" ]]; then
  if DISPATCH_CALLS_MUTATION_RUN=1 bash "$0" >/dev/null 2>&1; then
    echo "dispatch internal-call mutation unexpectedly survived" >&2
    exit 1
  fi
  echo "dispatch internal-call mutation rejected"
fi
